// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type FlexiblePageDocumentDataSlicesSlice =
  | CtaSlice
  | FeaturedServicesSlice
  | QuoteSlice
  | AdvantageSlice
  | HeroSlice;

/**
 * Content for Flexible Page documents
 */
interface FlexiblePageDocumentData {
  /**
   * Slice Zone field in *Flexible Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: flexiblePage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<FlexiblePageDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Flexible Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: flexiblePage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Flexible Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: flexiblePage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Flexible Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: flexiblePage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Flexible Page document from Prismic
 *
 * - **API ID**: `flexiblePage`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FlexiblePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<FlexiblePageDocumentData>,
    "flexiblePage",
    Lang
  >;

type ServiceDocumentDataSlicesSlice = ServiceHeaderSlice;

/**
 * Content for Service documents
 */
interface ServiceDocumentData {
  /**
   * name field in *Service*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * featured description field in *Service*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service.featuredDescription
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  featuredDescription: prismic.RichTextField;

  /**
   * featured icon field in *Service*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service.featuredIcon
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  featuredIcon: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Service*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: service.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ServiceDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Service*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: service.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Service*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Service*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: service.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Service document from Prismic
 *
 * - **API ID**: `service`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServiceDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ServiceDocumentData>,
    "service",
    Lang
  >;

export type AllDocumentTypes = FlexiblePageDocument | ServiceDocument;

/**
 * Primary content in *Advantage → Primary*
 */
export interface AdvantageSliceDefaultPrimary {
  /**
   * heading field in *Advantage → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: advantage.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * button text field in *Advantage → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: advantage.primary.buttonText
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonText: prismic.KeyTextField;

  /**
   * button link field in *Advantage → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: advantage.primary.buttonLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonLink: prismic.LinkField;
}

/**
 * Primary content in *Advantage → Items*
 */
export interface AdvantageSliceDefaultItem {
  /**
   * advantage heading field in *Advantage → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: advantage.items[].advantageHeading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  advantageHeading: prismic.TitleField;

  /**
   * advantage description field in *Advantage → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: advantage.items[].advantageDescription
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  advantageDescription: prismic.RichTextField;
}

/**
 * Default variation for Advantage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AdvantageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AdvantageSliceDefaultPrimary>,
  Simplify<AdvantageSliceDefaultItem>
>;

/**
 * Slice variation for *Advantage*
 */
type AdvantageSliceVariation = AdvantageSliceDefault;

/**
 * Advantage Shared Slice
 *
 * - **API ID**: `advantage`
 * - **Description**: Advantage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AdvantageSlice = prismic.SharedSlice<
  "advantage",
  AdvantageSliceVariation
>;

/**
 * Primary content in *Cta → Primary*
 */
export interface CtaSliceDefaultPrimary {
  /**
   * pre heading field in *Cta → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.primary.preHeading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  preHeading: prismic.RichTextField;

  /**
   * heading field in *Cta → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * body text field in *Cta → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.primary.bodyText
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  bodyText: prismic.RichTextField;

  /**
   * button text field in *Cta → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.primary.buttonText
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonText: prismic.KeyTextField;

  /**
   * button link field in *Cta → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.primary.buttonLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonLink: prismic.LinkField;
}

/**
 * Default variation for Cta Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CtaSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Cta*
 */
type CtaSliceVariation = CtaSliceDefault;

/**
 * Cta Shared Slice
 *
 * - **API ID**: `cta`
 * - **Description**: Cta
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaSlice = prismic.SharedSlice<"cta", CtaSliceVariation>;

/**
 * Primary content in *FeaturedServices → Primary*
 */
export interface FeaturedServicesSliceDefaultPrimary {
  /**
   * heading field in *FeaturedServices → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_services.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;
}

/**
 * Primary content in *FeaturedServices → Items*
 */
export interface FeaturedServicesSliceDefaultItem {
  /**
   * service field in *FeaturedServices → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_services.items[].service
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  service: prismic.ContentRelationshipField<"service">;
}

/**
 * Default variation for FeaturedServices Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedServicesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeaturedServicesSliceDefaultPrimary>,
  Simplify<FeaturedServicesSliceDefaultItem>
>;

/**
 * Slice variation for *FeaturedServices*
 */
type FeaturedServicesSliceVariation = FeaturedServicesSliceDefault;

/**
 * FeaturedServices Shared Slice
 *
 * - **API ID**: `featured_services`
 * - **Description**: FeaturedServices
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedServicesSlice = prismic.SharedSlice<
  "featured_services",
  FeaturedServicesSliceVariation
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * image field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *Quote → Primary*
 */
export interface QuoteSliceDefaultPrimary {
  /**
   * heading field in *Quote → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quote.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;
}

/**
 * Default variation for Quote Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type QuoteSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<QuoteSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Quote*
 */
type QuoteSliceVariation = QuoteSliceDefault;

/**
 * Quote Shared Slice
 *
 * - **API ID**: `quote`
 * - **Description**: Quote
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type QuoteSlice = prismic.SharedSlice<"quote", QuoteSliceVariation>;

/**
 * Primary content in *ServiceHeader → Primary*
 */
export interface ServiceHeaderSliceDefaultPrimary {
  /**
   * heading field in *ServiceHeader → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: service_header.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * body text field in *ServiceHeader → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_header.primary.bodyText
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  bodyText: prismic.RichTextField;

  /**
   * stats number field in *ServiceHeader → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: service_header.primary.statsNumber
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  statsNumber: prismic.NumberField;

  /**
   * stats unit field in *ServiceHeader → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_header.primary.statsUnit
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  statsUnit: prismic.KeyTextField;

  /**
   * stats caption field in *ServiceHeader → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_header.primary.statsCaption
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  statsCaption: prismic.KeyTextField;
}

/**
 * Default variation for ServiceHeader Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceHeaderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServiceHeaderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ServiceHeader*
 */
type ServiceHeaderSliceVariation = ServiceHeaderSliceDefault;

/**
 * ServiceHeader Shared Slice
 *
 * - **API ID**: `service_header`
 * - **Description**: ServiceHeader
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceHeaderSlice = prismic.SharedSlice<
  "service_header",
  ServiceHeaderSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      FlexiblePageDocument,
      FlexiblePageDocumentData,
      FlexiblePageDocumentDataSlicesSlice,
      ServiceDocument,
      ServiceDocumentData,
      ServiceDocumentDataSlicesSlice,
      AllDocumentTypes,
      AdvantageSlice,
      AdvantageSliceDefaultPrimary,
      AdvantageSliceDefaultItem,
      AdvantageSliceVariation,
      AdvantageSliceDefault,
      CtaSlice,
      CtaSliceDefaultPrimary,
      CtaSliceVariation,
      CtaSliceDefault,
      FeaturedServicesSlice,
      FeaturedServicesSliceDefaultPrimary,
      FeaturedServicesSliceDefaultItem,
      FeaturedServicesSliceVariation,
      FeaturedServicesSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      QuoteSlice,
      QuoteSliceDefaultPrimary,
      QuoteSliceVariation,
      QuoteSliceDefault,
      ServiceHeaderSlice,
      ServiceHeaderSliceDefaultPrimary,
      ServiceHeaderSliceVariation,
      ServiceHeaderSliceDefault,
    };
  }
}
