// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  advantage: dynamic(() => import("./Advantage")),
  cta: dynamic(() => import("./Cta")),
  featured_lists: dynamic(() => import("./FeaturedLists")),
  featured_services: dynamic(() => import("./FeaturedServices")),
  hero: dynamic(() => import("./Hero")),
  quote: dynamic(() => import("./Quote")),
  service_header: dynamic(() => import("./ServiceHeader")),
  steps: dynamic(() => import("./Steps")),
  team_lists: dynamic(() => import("./TeamLists")),
  team_partners: dynamic(() => import("./TeamPartners")),
};
