// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  advantage: dynamic(() => import("./Advantage")),
  cta: dynamic(() => import("./Cta")),
  featured_lists: dynamic(() => import("./FeaturedLists")),
  featured_services: dynamic(() => import("./FeaturedServices")),
  footer_navigation_item: dynamic(() => import("./FooterNavigationItem")),
  hero: dynamic(() => import("./Hero")),
  navigation_item: dynamic(() => import("./NavigationItem")),
  quote: dynamic(() => import("./Quote")),
  service_header: dynamic(() => import("./ServiceHeader")),
  services_lists: dynamic(() => import("./ServicesLists")),
  simple_text_field: dynamic(() => import("./SimpleTextField")),
  steps: dynamic(() => import("./Steps")),
  team_lists: dynamic(() => import("./TeamLists")),
  team_partners: dynamic(() => import("./TeamPartners")),
};
